# Generated by Django 3.2 on 2021-04-27 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for category', max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The question', max_length=2000)),
                ('answer', models.TextField(help_text='Answer to the question', max_length=2000)),
                ('category', models.ForeignKey(help_text='Category this question belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.category')),
            ],
        ),
    ]
