# Generated by Django 3.2 on 2021-04-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210427_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ignore_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
