# Generated by Django 3.2 on 2021-04-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_question_ignore_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ignore_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
