# Generated by Django 3.2 on 2021-05-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_question_ignore_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hide_indefinitely',
            field=models.BooleanField(default=False),
        ),
    ]
