# Generated by Django 3.2 on 2021-05-22 01:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_question_hide_indefinitely'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
